version: '3.8'

services:
  measurement:
    build:
      context: .
      dockerfile: dockerfile
    command: ["sh", "/package/measure.sh"]
    volumes:
      - ./package:/package
      - /lib/modules:/lib/modules
